version: '3.9'

services:

  db:
    build: .
    container_name: onlinestore_db
    image: onlinestore
    restart: always
    ports:
      - 3307:3306
    volumes:
      - .\db_data:/var/lib/mysql
    networks:
      - ciricefp

networks:
  ciricefp:
    driver: bridge

name: onlinestore_service
